const PALETTE=["#2d3a52","#4f6b95","#7f9bbf","#b3c4dc","#8d8f94","#c9c9c4"];
if(window.Chart){Chart.defaults.font.family='"IBM Plex Sans",system-ui,sans-serif';Chart.defaults.color="#5f6772"}
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbw7zTgelcTGXpUv0KESZTSV6aTyLVA-XQMDOHg2Ozru2-6fexKwYPTepeutnAzDx0t-/exec';

const EMPTY=()=>({lancamentos:[],estimativas:[],orcamentos:[]});
const state={data:EMPTY(),apiUrl:APPS_SCRIPT_URL,token:null,user:null,charts:{},period:"month"};
const categories=["Operacional","Marketing","Pessoal","Impostos","Aluguel","Tecnologia","Fornecedores","Vendas","Serviços","Outros"];
const $=id=>document.getElementById(id);
const brl=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
const hhmm=()=>new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});
async function apiRaw(action,payload={}){try{const r=await fetch(state.apiUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token:state.token,...payload})});const j=await r.json();if(j&&j.error==="Sessão expirada"&&state.token)lock("Sua sessão expirou. Entre novamente.");return j}catch(e){return {ok:false,error:"Falha na conexão"}}}
const LABELS={login:"Entrando…",register:"Criando conta…",getData:"Carregando seus dados…",saveData:"Salvando na nuvem…",logout:"Saindo…"};
let busy=0,slowT;
function busyOn(a){busy++;const base=LABELS[a]||"Carregando…";$("loaderText").textContent=base;$("loader").classList.add("show");clearTimeout(slowT);slowT=setTimeout(()=>{if(busy)$("loaderText").textContent=base+" o Google pode levar alguns segundos"},4000)}
function busyOff(){busy=Math.max(0,busy-1);if(!busy){clearTimeout(slowT);$("loader").classList.remove("show")}}
async function api(a,p={}){busyOn(a);try{return await apiRaw(a,p)}finally{busyOff()}}
async function sync(){const r=await api("getData");if(r?.ok&&r.data){state.data={...EMPTY(),...r.data};$("lastSync").textContent="Sincronizado com a nuvem • "+hhmm();toast("Dados atualizados")}else if(state.token){$("lastSync").textContent="Falha ao sincronizar"}renderAll()}
async function persist(){const r=await api("saveData",{data:state.data});if(!r?.ok){if(state.token){toast("Não foi possível salvar na nuvem");await sync()}throw new Error("save")}$("lastSync").textContent="Salvo na nuvem • "+hhmm()}
function dateObj(s){return new Date((s||"2000-01-01")+"T12:00:00")}
function inPeriod(item){const d=dateObj(item.data);const now=new Date();if(state.period==="all")return true;if(state.period==="year")return d.getFullYear()===now.getFullYear();if(state.period==="quarter")return d.getFullYear()===now.getFullYear()&&Math.floor(d.getMonth()/3)===Math.floor(now.getMonth()/3);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()}
function filtered(){return state.data.lancamentos.filter(inPeriod)}
function renderDashboard(){const list=filtered(),rev=list.filter(x=>x.tipo==="Receita").reduce((a,x)=>a+Number(x.valor),0),exp=list.filter(x=>x.tipo==="Despesa").reduce((a,x)=>a+Number(x.valor),0),profit=rev-exp;
$("kpiRevenue").textContent=brl(rev);$("kpiExpense").textContent=brl(exp);$("kpiProfit").textContent=brl(profit);$("kpiMargin").textContent=(rev?(profit/rev*100):0).toFixed(1)+"%";
const recent=[...state.data.lancamentos].sort((a,b)=>dateObj(b.data)-dateObj(a.data)).slice(0,7);
$("recentTable").innerHTML=recent.length?recent.map(rowHtml).join(""):`<tr><td colspan="5" class="empty">Nenhum lançamento cadastrado.</td></tr>`;
const months=[];for(let i=5;i>=0;i--){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);months.push(d)}
const labels=months.map(d=>d.toLocaleDateString("pt-BR",{month:"short"}));const rv=months.map(d=>sumMonth(d,"Receita")),ex=months.map(d=>sumMonth(d,"Despesa"));
draw("cashflowChart","bar",{labels,datasets:[{label:"Receitas",data:rv,backgroundColor:"#2f8f68",borderRadius:2},{label:"Despesas",data:ex,backgroundColor:"#c9574f",borderRadius:2}]});
const cats={};list.filter(x=>x.tipo==="Despesa").forEach(x=>cats[x.categoria]=(cats[x.categoria]||0)+Number(x.valor));draw("categoryChart","doughnut",{labels:Object.keys(cats),datasets:[{data:Object.values(cats),backgroundColor:PALETTE,borderWidth:2,borderColor:"#fff"}]});
}
function sumMonth(d,t){return state.data.lancamentos.filter(x=>{const z=dateObj(x.data);return z.getFullYear()===d.getFullYear()&&z.getMonth()===d.getMonth()&&x.tipo===t}).reduce((a,x)=>a+Number(x.valor),0)}
function rowHtml(x){return `<tr><td>${fmtDate(x.data)}</td><td>${esc(x.descricao)}</td><td>${esc(x.categoria)}</td><td><span class="badge ${x.tipo.toLowerCase()}">${x.tipo}</span></td><td>${brl(x.valor)}</td></tr>`}
function renderLaunches(){const q=($("searchInput")?.value||"").toLowerCase(),tf=$("typeFilter")?.value||"";const list=state.data.lancamentos.filter(x=>(!tf||x.tipo===tf)&&JSON.stringify(x).toLowerCase().includes(q)).sort((a,b)=>dateObj(b.data)-dateObj(a.data));$("launchTable").innerHTML=list.length?list.map(x=>`<tr><td>${fmtDate(x.data)}</td><td>${esc(x.descricao)}</td><td>${esc(x.categoria)}</td><td>${esc(x.parte)}</td><td><span class="badge ${x.tipo.toLowerCase()}">${x.tipo}</span></td><td>${brl(x.valor)}</td><td><button class="action-btn" onclick="editLaunch('${x.id}')">Editar</button> <button class="action-btn delete" onclick="deleteLaunch('${x.id}')">Excluir</button></td></tr>`).join(""):`<tr><td colspan="7" class="empty">Nenhum lançamento encontrado.</td></tr>`}
function renderRevenue(){const list=state.data.lancamentos.filter(x=>x.tipo==="Receita").sort((a,b)=>dateObj(b.data)-dateObj(a.data));$("revenueTotal").textContent=brl(list.filter(inPeriod).reduce((a,x)=>a+Number(x.valor),0));$("revenueForecast").textContent=brl(state.data.estimativas.filter(x=>x.tipo==="Receita").reduce((a,x)=>a+Number(x.valor),0));$("revenueTable").innerHTML=list.length?list.map(x=>`<tr><td>${fmtDate(x.data)}</td><td>${esc(x.parte)}</td><td>${esc(x.descricao)}</td><td>${esc(x.status)}</td><td>${brl(x.valor)}</td></tr>`).join(""):`<tr><td colspan="5" class="empty">Nenhuma receita cadastrada.</td></tr>`}
function renderExpenses(){const list=state.data.lancamentos.filter(x=>x.tipo==="Despesa").sort((a,b)=>dateObj(b.data)-dateObj(a.data));const p=list.filter(inPeriod);$("expenseTotal").textContent=brl(p.reduce((a,x)=>a+Number(x.valor),0));const cats={};p.forEach(x=>cats[x.categoria]=(cats[x.categoria]||0)+Number(x.valor));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];$("topCategory").textContent=top?`${top[0]} • ${brl(top[1])}`:"—";$("expenseTable").innerHTML=list.length?list.map(x=>`<tr><td>${fmtDate(x.data)}</td><td>${esc(x.parte)}</td><td>${esc(x.descricao)}</td><td>${esc(x.categoria)}</td><td>${brl(x.valor)}</td></tr>`).join(""):`<tr><td colspan="5" class="empty">Nenhuma despesa cadastrada.</td></tr>`}
function renderForecast(){const f=state.data.estimativas||[];$("forecastTable").innerHTML=f.length?f.sort((a,b)=>a.mes.localeCompare(b.mes)).map(x=>`<tr><td>${monthLabel(x.mes)}</td><td>${x.tipo}</td><td>${esc(x.descricao)}</td><td>${brl(x.valor)}</td><td><button class="action-btn delete" onclick="deleteForecast('${x.id}')">Excluir</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">Nenhuma estimativa cadastrada.</td></tr>`;
const months=[...new Set(f.map(x=>x.mes))].sort().slice(-6);const labels=months.map(monthLabel);draw("forecastChart","bar",{labels,datasets:[{label:"Receita estimada",backgroundColor:"#2f8f68",borderRadius:2,data:months.map(m=>f.filter(x=>x.mes===m&&x.tipo==="Receita").reduce((a,x)=>a+Number(x.valor),0))},{label:"Despesa estimada",backgroundColor:"#c9574f",borderRadius:2,data:months.map(m=>f.filter(x=>x.mes===m&&x.tipo==="Despesa").reduce((a,x)=>a+Number(x.valor),0))}]});
$("forecastSummary").innerHTML=months.length?months.map(m=>`<div class="forecast-line"><span>${monthLabel(m)}</span><strong>${brl(f.filter(x=>x.mes===m).reduce((a,x)=>a+(x.tipo==="Receita"?1:-1)*Number(x.valor),0))}</strong></div>`).join(""):"<p class='hint'>Cadastre estimativas para visualizar o planejamento.</p>"}
function renderReport(){const list=state.data.lancamentos.filter(x=>{const s=$("reportStart").value,e=$("reportEnd").value,t=$("reportType").value;return(!s||x.data>=s)&&(!e||x.data<=e)&&(!t||x.tipo===t)}),rev=list.filter(x=>x.tipo==="Receita").reduce((a,x)=>a+Number(x.valor),0),exp=list.filter(x=>x.tipo==="Despesa").reduce((a,x)=>a+Number(x.valor),0);$("reportPreview").innerHTML=`<div class="cards mini"><div class="card"><span>Receitas</span><strong>${brl(rev)}</strong></div><div class="card"><span>Despesas</span><strong>${brl(exp)}</strong></div></div><p>${list.length} lançamentos encontrados. Resultado: <b>${brl(rev-exp)}</b>.</p>`}
function draw(id,type,data){const el=$(id);if(!el)return;if(state.charts[id])state.charts[id].destroy();state.charts[id]=new Chart(el,{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{boxWidth:10,font:{size:12}}}},scales:type==="doughnut"?{}:{y:{beginAtZero:true,border:{display:false},grid:{color:"#eceef2"},ticks:{callback:v=>"R$ "+Number(v).toLocaleString("pt-BR")}}}}})}
function renderAll(){renderDashboard();renderLaunches();renderRevenue();renderExpenses();renderForecast();renderQuotes();renderReport()}
function openLaunch(type="Despesa",item=null){$("modalTitle").textContent=item?"Editar lançamento":"Novo lançamento";$("editId").value=item?.id||"";$("formType").value=item?.tipo||type;$("formDate").value=item?.data||today();$("formDescription").value=item?.descricao||"";$("formCategory").value=item?.categoria||categories[0];$("formParty").value=item?.parte||"";$("formAmount").value=item?.valor||"";$("formStatus").value=item?.status||(type==="Receita"?"Recebido":"Pago");$("formPayment").value=item?.pagamento||"";$("formNote").value=item?.observacao||"";$("modalBackdrop").classList.add("show")}
async function submitLaunch(e){e.preventDefault();const id=$("editId").value||uid(),x={id,tipo:$("formType").value,data:$("formDate").value,descricao:$("formDescription").value,categoria:$("formCategory").value,parte:$("formParty").value,valor:Number($("formAmount").value),status:$("formStatus").value,pagamento:$("formPayment").value,observacao:$("formNote").value};const idx=state.data.lancamentos.findIndex(a=>a.id===id);if(idx>=0)state.data.lancamentos[idx]=x;else state.data.lancamentos.push(x);await persist();$("modalBackdrop").classList.remove("show");toast("Lançamento salvo");renderAll()}
window.editLaunch=id=>{const x=state.data.lancamentos.find(a=>a.id===id);if(x)openLaunch(x.tipo,x)}
window.deleteLaunch=async id=>{if(!confirm("Excluir este lançamento?"))return;state.data.lancamentos=state.data.lancamentos.filter(x=>x.id!==id);await persist();toast("Lançamento excluído");renderAll()}
window.deleteForecast=async id=>{state.data.estimativas=state.data.estimativas.filter(x=>x.id!==id);await persist();toast("Estimativa excluída");renderAll()}
function openForecast(){$("forecastMonth").value=new Date().toISOString().slice(0,7);$("forecastModal").classList.add("show")}
async function submitForecast(e){e.preventDefault();state.data.estimativas.push({id:uid(),mes:$("forecastMonth").value,tipo:$("forecastType").value,descricao:$("forecastDescription").value,valor:Number($("forecastAmount").value)});await persist();$("forecastModal").classList.remove("show");toast("Estimativa salva");renderAll()}

function quoteTotal(q){return (q.itens||[]).reduce((a,i)=>a+(Number(i.quantidade)||0)*(Number(i.preco)||0),0)}
function quoteNumber(q){return q.numero||("ORC-"+String(q.id||"").slice(-6).toUpperCase())}
function renderQuotes(){
 const qs=state.data.orcamentos||[];
 $("quoteCount").textContent=qs.length;
 $("quoteTotal").textContent=brl(qs.reduce((a,q)=>a+quoteTotal(q),0));
 $("quoteTable").innerHTML=qs.length?qs.slice().sort((a,b)=>dateObj(b.data)-dateObj(a.data)).map(q=>`
 <tr><td><b>${quoteNumber(q)}</b></td><td>${fmtDate(q.data)}</td><td>${esc(q.cliente)}</td><td>${fmtDate(q.validade)}</td>
 <td><span class="badge ${q.status==="Aprovado"?"receita":q.status==="Recusado"?"despesa":""}">${esc(q.status)}</span></td>
 <td>${brl(quoteTotal(q))}</td><td>
 <button class="action-btn" onclick="editQuote('${q.id}')">Editar</button>
 <button class="action-btn" onclick="copyQuoteLink('${q.id}')">Link</button>
 <button class="action-btn" onclick="pdfQuote('${q.id}')">PDF</button>
 <button class="action-btn delete" onclick="deleteQuote('${q.id}')">Excluir</button></td></tr>`).join(""):`<tr><td colspan="7" class="empty">Nenhum orçamento cadastrado.</td></tr>`;
}
function addQuoteItem(item={}){const row=document.createElement("div");row.className="quote-item";row.innerHTML=`
 <label>Descrição<input class="qi-desc" required value="${esc(item.descricao||"")}" placeholder="Produto ou serviço"></label>
 <label>Qtd.<input class="qi-qty" type="number" min="0" step="0.01" value="${item.quantidade??1}"></label>
 <label>Preço unitário<input class="qi-price" type="number" min="0" step="0.01" value="${item.preco??0}"></label>
 <label>Total<input class="qi-total" readonly value="${brl((item.quantidade||1)*(item.preco||0))}"></label>
 <button type="button" class="remove-item">×</button>`;
 $("quoteItems").appendChild(row);
 row.querySelectorAll("input").forEach(i=>i.addEventListener("input",updateQuoteTotals));
 row.querySelector(".remove-item").onclick=()=>{row.remove();updateQuoteTotals()};
 updateQuoteTotals();
}
function updateQuoteTotals(){$("quoteItems").querySelectorAll(".quote-item").forEach(r=>{const q=Number(r.querySelector(".qi-qty").value)||0,p=Number(r.querySelector(".qi-price").value)||0;r.querySelector(".qi-total").value=brl(q*p)});let total=0;$("quoteItems").querySelectorAll(".quote-item").forEach(r=>total+=(Number(r.querySelector(".qi-qty").value)||0)*(Number(r.querySelector(".qi-price").value)||0));$("quoteGrandTotal").textContent=brl(total)}
function openQuote(q=null){
 $("quoteModalTitle").textContent=q?"Editar orçamento":"Novo orçamento";$("quoteId").value=q?.id||uid();
 $("quoteClient").value=q?.cliente||"";$("quoteDate").value=q?.data||today();$("quoteValidity").value=q?.validade||new Date(Date.now()+7*86400000).toISOString().slice(0,10);
 $("quoteStatus").value=q?.status||"Rascunho";$("quoteContact").value=q?.contato||"";$("quoteEmail").value=q?.email||"";$("quoteNotes").value=q?.observacoes||"";
 $("quoteItems").innerHTML="";(q?.itens?.length?q.itens:[{}]).forEach(addQuoteItem);$("quoteModal").classList.add("show");
}
async function submitQuote(e){e.preventDefault();const id=$("quoteId").value;const q={id,numero:"ORC-"+id.slice(-6).toUpperCase(),cliente:$("quoteClient").value,data:$("quoteDate").value,validade:$("quoteValidity").value,status:$("quoteStatus").value,contato:$("quoteContact").value,email:$("quoteEmail").value,observacoes:$("quoteNotes").value,itens:[...$("quoteItems").querySelectorAll(".quote-item")].map(r=>({descricao:r.querySelector(".qi-desc").value,quantidade:Number(r.querySelector(".qi-qty").value)||0,preco:Number(r.querySelector(".qi-price").value)||0}))};const i=(state.data.orcamentos||[]).findIndex(x=>x.id===id);if(i>=0)state.data.orcamentos[i]=q;else state.data.orcamentos.push(q);await persist();$("quoteModal").classList.remove("show");toast("Orçamento salvo");renderAll()}
window.editQuote=id=>{const q=state.data.orcamentos.find(x=>x.id===id);if(q)openQuote(q)}
window.deleteQuote=async id=>{if(!confirm("Excluir este orçamento?"))return;state.data.orcamentos=state.data.orcamentos.filter(x=>x.id!==id);await persist();toast("Orçamento excluído");renderAll()}
function publicQuoteUrl(q){const data=btoa(unescape(encodeURIComponent(JSON.stringify(q))));return location.href.split("#")[0]+"#orcamento="+encodeURIComponent(data)}
window.copyQuoteLink=async id=>{const q=state.data.orcamentos.find(x=>x.id===id);if(!q)return;const url=publicQuoteUrl(q);try{await navigator.clipboard.writeText(url);toast("Link copiado para enviar ao cliente")}catch{prompt("Copie o link do orçamento:",url)}}
function pdfQuote(id){const q=state.data.orcamentos.find(x=>x.id===id);if(!q)return;const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(21);doc.text("NIDU",14,18);doc.setFontSize(12);doc.text("ORÇAMENTO "+quoteNumber(q),14,28);doc.setFontSize(9);doc.text(`Cliente: ${q.cliente}`,14,37);doc.text(`Data: ${fmtDate(q.data)}   Validade: ${fmtDate(q.validade)}`,14,43);doc.autoTable({startY:50,head:[["Descrição","Qtd.","Preço unit.","Total"]],body:(q.itens||[]).map(i=>[i.descricao,i.quantidade,brl(i.preco),brl(i.quantidade*i.preco)])});let y=doc.lastAutoTable.finalY+12;doc.setFontSize(14);doc.text("Total: "+brl(quoteTotal(q)),145,y,{align:"right"});if(q.observacoes){doc.setFontSize(9);doc.text("Observações:",14,y+15);doc.text(doc.splitTextToSize(q.observacoes,180),14,y+21)}doc.save(`${quoteNumber(q)}.pdf`)}
function showPublicQuote(){
 const hash=location.hash;if(!hash.startsWith("#orcamento="))return;try{const q=JSON.parse(decodeURIComponent(escape(atob(decodeURIComponent(hash.slice(11))))));document.body.innerHTML=`<div class="public-quote"><div class="public-box"><div class="brand">NIDU</div><div class="public-head"><div><h1>Orçamento ${quoteNumber(q)}</h1><p>Emitido em ${fmtDate(q.data)} • Validade: ${fmtDate(q.validade)}</p></div><span class="badge">${esc(q.status)}</span></div><div class="public-client"><b>Cliente</b><br>${esc(q.cliente)}${q.contato?"<br>"+esc(q.contato):""}</div><table><thead><tr><th>Descrição</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>${(q.itens||[]).map(i=>`<tr><td>${esc(i.descricao)}</td><td>${i.quantidade}</td><td>${brl(i.preco)}</td><td>${brl(i.quantidade*i.preco)}</td></tr>`).join("")}</tbody></table><div class="public-total">Total <strong>${brl(quoteTotal(q))}</strong></div>${q.observacoes?`<div class="public-notes"><b>Observações</b><p>${esc(q.observacoes)}</p></div>`:""}<div class="public-actions"><button onclick="window.print()">Imprimir / Salvar PDF</button></div></div></div>`}catch(e){console.error(e)}}


function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$("view-"+v).classList.add("active");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));const names={dashboard:["Dashboard","Visão geral do seu negócio"],lancamentos:["Lançamentos","Controle suas entradas e saídas"],receitas:["Receitas","Faturamento e entradas"],despesas:["Despesas","Custos e gastos"],estimativas:["Estimativas","Planejamento financeiro"],orcamentos:["Orçamentos","Propostas comerciais"],relatorios:["Relatórios","Análises e documentos"],config:["Configurações","Integrações e preferências"]};$("pageTitle").textContent=names[v][0];$("pageSubtitle").textContent=names[v][1];if(v==="relatorios")renderReport();$("sidebar").classList.remove("open")}
function fmtDate(s){return s?dateObj(s).toLocaleDateString("pt-BR"):"—"}function monthLabel(s){if(!s)return"—";const [y,m]=s.split("-");return new Date(Number(y),Number(m)-1,1).toLocaleDateString("pt-BR",{month:"short",year:"2-digit"})}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function pdf(){const {jsPDF}=window.jspdf,doc=new jsPDF();const list=state.data.lancamentos.filter(x=>{const s=$("reportStart").value,e=$("reportEnd").value,t=$("reportType").value;return(!s||x.data>=s)&&(!e||x.data<=e)&&(!t||x.tipo===t)});const rev=list.filter(x=>x.tipo==="Receita").reduce((a,x)=>a+Number(x.valor),0),exp=list.filter(x=>x.tipo==="Despesa").reduce((a,x)=>a+Number(x.valor),0);doc.setFontSize(20);doc.text("NIDU",14,18);doc.setFontSize(11);doc.text("Relatório financeiro",14,27);doc.setFontSize(9);doc.text(`Gerado em ${new Date().toLocaleString("pt-BR")}`,14,34);doc.autoTable({startY:42,head:[["Indicador","Valor"]],body:[["Faturamento",brl(rev)],["Despesas",brl(exp)],["Resultado",brl(rev-exp)],["Margem",rev?((rev-exp)/rev*100).toFixed(1)+"%":"0,0%"]]});doc.autoTable({startY:85,head:[["Data","Descrição","Categoria","Tipo","Valor"]],body:list.map(x=>[fmtDate(x.data),x.descricao,x.categoria,x.tipo,brl(x.valor)])});doc.save(`relatorio-financeiro-${today()}.pdf`)}
function init(){$("formCategory").innerHTML=categories.map(x=>`<option>${x}</option>`).join("");$("formDate").value=today();$("reportStart").value=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);$("reportEnd").value=today();document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll("[data-view-link]").forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));document.querySelectorAll("[data-open-modal]").forEach(b=>b.onclick=()=>b.dataset.openModal==="estimativa"?openForecast():openLaunch(b.dataset.openModal==="receita"?"Receita":"Despesa"));$("quickAdd")?.addEventListener("click",()=>openLaunch());$("newLaunchBtn")?.addEventListener("click",()=>openLaunch());$("newQuoteBtn")?.addEventListener("click",()=>openQuote());$("addQuoteItem")?.addEventListener("click",()=>addQuoteItem());$("closeQuote")?.addEventListener("click",()=>$("quoteModal").classList.remove("show"));$("cancelQuote")?.addEventListener("click",()=>$("quoteModal").classList.remove("show"));$("quoteForm")?.addEventListener("submit",submitQuote);$("closeModal")?.addEventListener("click",()=>$("modalBackdrop").classList.remove("show"));$("cancelModal")?.addEventListener("click",()=>$("modalBackdrop").classList.remove("show"));$("closeForecast")?.addEventListener("click",()=>$("forecastModal").classList.remove("show"));$("cancelForecast")?.addEventListener("click",()=>$("forecastModal").classList.remove("show"));$("launchForm")?.addEventListener("submit",submitLaunch);$("forecastForm")?.addEventListener("submit",submitForecast);$("periodSelect")?.addEventListener("change",e=>{state.period=e.target.value;renderAll()});$("searchInput")?.addEventListener("input",renderLaunches);$("typeFilter")?.addEventListener("change",renderLaunches);$("refreshBtn")?.addEventListener("click",sync);$("pdfBtn")?.addEventListener("click",pdf);["reportStart","reportEnd","reportType"].forEach(id=>$(id)?.addEventListener("change",renderReport));$("mobileMenu")?.addEventListener("click",()=>$("sidebar").classList.toggle("open"));}
if(location.hash.startsWith("#orcamento=")){showPublicQuote()}else{init();initAuth();lock()}

document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal-backdrop.show").forEach(m=>m.classList.remove("show"))});
document.querySelectorAll(".modal-backdrop").forEach(m=>m.addEventListener("mousedown",e=>{if(e.target===m)m.classList.remove("show")}));

/* ---------- autenticação (dados só na nuvem; token só em memória) ---------- */
let authMode="login";
function setMode(m){authMode=m;document.querySelectorAll(".reg-only").forEach(x=>x.hidden=m!=="register");$("authSubmit").textContent=m==="login"?"Entrar":"Criar conta";$("authToggle").textContent=m==="login"?"Criar uma conta":"Já tenho conta";$("authTitle").textContent=m==="login"?"Entre para acessar seu painel.":"Crie sua conta.";$("authError").textContent=""}
function lock(msg){state.token=null;state.user=null;state.data=EMPTY();document.body.classList.add("locked");$("authPass").value="";$("authError").textContent=msg||"";document.querySelectorAll(".modal-backdrop.show").forEach(m=>m.classList.remove("show"))}
function unlock(r){state.token=r.token;state.user=r.nome;state.data={...EMPTY(),...r.data};document.body.classList.remove("locked");$("userName").textContent=r.nome||"";$("lastSync").textContent="Sincronizado com a nuvem • "+hhmm();showView("dashboard");renderAll()}
function initAuth(){
 $("authToggle").onclick=()=>setMode(authMode==="login"?"register":"login");
 $("logoutBtn").onclick=async()=>{await api("logout");lock()};
 $("authForm").onsubmit=async e=>{e.preventDefault();$("authError").textContent="";$("authSubmit").disabled=true;$("authSubmit").classList.add("loading");const r=await api(authMode,{nome:$("authName").value,email:$("authEmail").value,password:$("authPass").value,code:$("authCode").value});$("authSubmit").disabled=false;$("authSubmit").classList.remove("loading");if(r?.ok)unlock(r);else $("authError").textContent=r?.error||"Falha na conexão"}
}
